#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1
PROG=/usr/sbin/watchdog_healthd

start_service() {
	procd_open_instance
	procd_set_param command $PROG
	procd_set_param respawn 3600 5 5
	procd_close_instance
}

stop_service() {
	killall watchdog_healthd 2>/dev/null
}
